Add selectionStart and selectionEnd variables to markdown input ref
Expensify/react-native-live-markdown pull request #176
Opened 2024-02-09 11:46 UTC by Skalakid

### Details

This PR fixes how our markdown text input tracks text selection and adds `selectionStart` and `selectionEnd` variables to input ref.

### Related Issues

https://github.com/Expensify/react-native-live-markdown/issues/173

### Manual Tests

Using reproduction code from the linked issue start changing the text selection. Verify in console if it returns correct values. Next, position your cursor at the beginning of the markdown text input and after clicking `arrow up`, verify if focus is changed into RN text input that is above

### Linked PRs

https://github.com/Expensify/App/issues/36173

2024-02-09 13:50 UTC, robertKozik approved these changes

2024-02-12 13:55 UTC, tomekzaw commented on src/MarkdownTextInput.web.tsx
> +      (divRef.current as HTMLInputElement).selectionEnd = selection.end;
Let's assign `divRef.current` to a new variable

2024-02-14 11:31 UTC, tomekzaw requested changes

2024-02-14 11:31 UTC, tomekzaw commented on src/MarkdownTextInput.web.tsx
> +      return selection;
```suggestion
```

2024-02-14 11:31 UTC, tomekzaw commented on src/MarkdownTextInput.web.tsx
> +
```suggestion
```

2024-02-14 11:31 UTC, tomekzaw commented on src/MarkdownTextInput.web.tsx
> +        if (onSelectionChange && selection) {
```suggestion
        updateSelection();
        if (onSelectionChange && contentSelection.current) {
```

2024-02-14 11:31 UTC, tomekzaw commented on src/MarkdownTextInput.web.tsx
> +        onKeyUp={handleKeyUp}
```suggestion
        onKeyUp={updateSelection}
```

2024-02-14 11:54 UTC, tomekzaw approved these changes
Thanks for fixing this!

2024-02-14 14:42 UTC, merged