Support multiple blockquotes & enable range grouping
Expensify/react-native-live-markdown pull request #196
Opened 2024-02-21 11:51 UTC by robertKozik

### Details

### Related Issues

GH_LINK

### Manual Tests

### Linked PRs

2024-02-21 14:19 UTC, tomekzaw requested changes

2024-02-21 14:19 UTC, tomekzaw commented on android/src/main/java/com/expensify/livemarkdown/MarkdownBlockquoteSpan.java
> +    for(int stripe = 0; stripe < nestLevel; stripe++) {
Let's add a space between `for` and `(` and maybe rename the variable?
```suggestion
    for (int level = 0; level < nestLevel; level++) {
```

2024-02-21 14:19 UTC, tomekzaw commented on android/src/main/java/com/expensify/livemarkdown/MarkdownBlockquoteSpan.java
> +      float shift = (borderWidth + marginLeft + paddingLeft) * stripe;
Let's make it consistent with `getLeadingMargin`.
```suggestion
      float shift = (marginLeft + borderWidth + paddingLeft) * stripe;
```

2024-02-21 14:19 UTC, tomekzaw commented on android/src/main/java/com/expensify/livemarkdown/MarkdownUtils.java
> +        String type = range.getString("style");
Let's stick to either `type` or `style`.
```suggestion
        String style = range.getString("style");
```

2024-02-21 14:19 UTC, tomekzaw commented on ios/MarkdownLayoutManager.mm
> +    __block int currentDepth = 0;
I believe we can move the declaration of `currentDepth` into `enumerateObjectsUsingBlock:`.
```suggestion
```

2024-02-21 14:19 UTC, tomekzaw commented on ios/MarkdownLayoutManager.mm
> +      currentDepth = [[item valueForKey:@"depth"] unsignedIntegerValue];
```suggestion
      NSUInteger depth = [[item valueForKey:@"depth"] unsignedIntegerValue];
```

2024-02-21 14:19 UTC, tomekzaw commented on ios/MarkdownLayoutManager.mm
> +      CGFloat nestShift = paddingLeft + width + markdownUtils.markdownStyle.blockquoteMarginLeft;
1. Let's rename the variable from `nestShift` to `shift` to be consistent with iOS.
2. We should also include `markdownUtils.markdownStyle.blockquotePaddingLeft` (blockquote padding) which is a different thing than `markdownUtils.backedTextInputView.textContainerInset.left` (text input padding). Let's assign all intermediate variables and change this line to:
```suggestion
      CGFloat shift = blockquoteMarginLeft + blockquoteBorderWidth + blockquotePaddingLeft;
```

2024-02-21 14:19 UTC, tomekzaw commented on types/global.d.ts
> +}; // style, location, length
Let's remove this comment since it's no longer relevant
```suggestion
};
```

2024-02-21 14:19 UTC, tomekzaw commented on types/global.d.ts
> +  style: string;
Let's use `MarkdownType` (perhaps it should be named `MarkdownStyle`?) here

2024-02-21 14:19 UTC, tomekzaw commented on ios/MarkdownLayoutManager.mm
> +        CGRect lineRect = CGRectMake(x + (strip * nestShift), y, width, height);
The idea behind these variables (`x`, `y`, `width`, `height`) was that they are calculated above and thus we don't need any calculations in `CGRectMake`. Please move the calculations outside of it.
```suggestion
        CGRect lineRect = CGRectMake(x, y, width, height);
```

2024-02-21 14:19 UTC, tomekzaw commented on ios/RCTMarkdownUtils.mm
> +      NSInteger depth = [[item valueForKey:@"depth"] unsignedIntegerValue] ?: 1;
Too many spaces
```suggestion
    NSInteger depth = [[item valueForKey:@"depth"] unsignedIntegerValue] ?: 1;
```

2024-02-21 14:19 UTC, tomekzaw commented on ios/RCTMarkdownUtils.mm
> +      paragraphStyle.headIndent = indent * depth;
I've noticed that here we were already using `indent` and you have introduced term `shift` for the same thing. Let's unify them.

2024-02-21 14:19 UTC, tomekzaw commented on ios/RCTMarkdownUtils.mm
> +      [_leveledBlockquoteRanges addObject: [NSDictionary dictionaryWithObjects:dictValues forKeys:keys]];
Let's use the short-hand syntax for creating dictionaries:
```suggestion
      [_leveledBlockquoteRanges addObject:@{
        @"range": @(range),
        @"depth": @(depth)
      }];
```

2024-02-21 14:19 UTC, tomekzaw commented on parser/index.ts
> +type Token = ['TEXT' | 'HTML', string, number?];
Why do we need `number?` here?

2024-02-21 14:19 UTC, tomekzaw commented on parser/index.ts
> +type Styles = 'bold' | 'italic' | 'strikethrough' | 'mention-here' | 'mention-user' | 'link' | 'code' | 'pre' | 'blockquote' | 'h1' | 'syntax';
```suggestion
type MarkdownStyle = 'bold' | 'italic' | 'strikethrough' | 'mention-here' | 'mention-user' | 'link' | 'code' | 'pre' | 'blockquote' | 'h1' | 'syntax';

```

2024-02-22 09:21 UTC, tomekzaw requested changes

2024-02-22 09:21 UTC, tomekzaw commented on ios/MarkdownLayoutManager.mm
> +      for(int level = 0; level < currentDepth; level++) {
```suggestion
      for (int level = 0; level < currentDepth; level++) {
```

2024-02-22 09:21 UTC, tomekzaw commented on ios/MarkdownLayoutManager.mm
> +        CGFloat x = paddingLeft + markdownUtils.markdownStyle.blockquoteMarginLeft + (level * shift);
It makes more sense to me with this ordering:
```suggestion
        CGFloat x = paddingLeft + (level * shift) + markdownUtils.markdownStyle.blockquoteMarginLeft;
```

2024-02-23 13:09 UTC, robertKozik commented
closed in favour of #202

2024-02-23 13:10 UTC, closed without merging