Diacritics fix
Expensify/react-native-live-markdown pull request #210
Opened 2024-03-04 09:58 UTC by BartoszGrajdek

### Details

### Related Issues

GH_LINK

### Manual Tests

### Linked PRs

2024-03-04 10:05 UTC, Skalakid submitted a review, later dismissed
LGTM

2024-03-04 10:07 UTC, tomekzaw commented on src/MarkdownTextInput.web.tsx
> +    const [isComposition, setIsComposition] = useState(false);
Looks like we never read `isComposition` during React render and we probably also don't want to trigger a React render when this changes. How about using `useRef` here instead?

2024-03-05 09:29 UTC, tomekzaw commented on src/MarkdownTextInput.web.tsx
> +    const compositionRef = useRef<boolean | null>(null);
Does it work if we initialize the ref with `false`?
```suggestion
    const compositionRef = useRef<boolean>(false);
```

2024-03-05 09:29 UTC, tomekzaw commented on src/MarkdownTextInput.web.tsx
> +    };
Can we memoize this callback so it's not regenerated on each render?
```suggestion
    const startComposition = useCallback(() => {
      compositionRef.current = true;
    }, []);
```

2024-03-05 10:51 UTC, tomekzaw commented
There seems to be some problem with text color in this case:

https://github.com/Expensify/react-native-live-markdown/assets/20516055/ae66fed0-ccfc-4266-b7b2-b3a3545ace73

2024-03-06 14:02 UTC, Skalakid approved these changes

2024-03-06 14:05 UTC, Skalakid requested changes
Placeholder color doesn't update when `placeholderTextColor` prop changes


https://github.com/Expensify/react-native-live-markdown/assets/39538890/ec24aa90-8678-4b2d-9f7c-00d47f07a8f0

2024-03-06 14:10 UTC, BartoszGrajdek commented
Fixed @Skalakid

2024-03-06 14:13 UTC, Skalakid submitted a review, later dismissed
LGTM

2024-03-06 15:32 UTC, tomekzaw approved these changes
Thanks for fixing this!

2024-03-06 16:50 UTC, merged