Add hybrid app support
Expensify/react-native-live-markdown pull request #476
Opened 2024-09-10 06:52 UTC by MrRefactor

### Details

Hybrid app support as a follow-up from `react-native 0.75` upgrade - more context [here](https://github.com/Expensify/App/pull/48626#pullrequestreview-2282496318)

### Related Issues

GH_LINK

### Manual Tests

### Linked PRs

2024-09-10 06:53 UTC, MrRefactor commented
I have read the CLA Document and I hereby sign the CLA

2024-09-10 06:54 UTC, MrRefactor commented
recheck

2024-09-10 17:58 UTC, tomekzaw requested changes

2024-09-10 17:58 UTC, tomekzaw commented on RNLiveMarkdown.podspec
>    if ENV['USE_FRAMEWORKS'] && ENV['RCT_NEW_ARCH_ENABLED']
```suggestion
  if ENV['USE_FRAMEWORKS'] == 'static' && ENV['RCT_NEW_ARCH_ENABLED'] == '1'
```

2024-09-10 17:58 UTC, tomekzaw commented on RNLiveMarkdown.podspec
> +    ]);
```suggestion
    ])
```

2024-09-11 07:55 UTC, tomekzaw reviewed
Waiting for @war-in's confirmation that this PR works in HybridApp

2024-09-11 08:15 UTC, tomekzaw commented on RNLiveMarkdown.podspec
> +  if ENV['USE_FRAMEWORKS'] == 'static' && ENV['RCT_NEW_ARCH_ENABLED'] == '1'
```suggestion
  if ENV['USE_FRAMEWORKS'] != nil && ENV['RCT_NEW_ARCH_ENABLED'] == '1'
```

2024-09-11 08:15 UTC, tomekzaw commented on RNLiveMarkdown.podspec
> +  if ENV['USE_FRAMEWORKS'] == 'static' && ENV['RCT_NEW_ARCH_ENABLED'] == '1'
```suggestion
  if ENV['USE_FRAMEWORKS'] != nil && ENV['RCT_NEW_ARCH_ENABLED'] == '1'
```

2024-09-11 08:17 UTC, tomekzaw requested changes

2024-09-11 08:17 UTC, tomekzaw commented on RNLiveMarkdown.podspec
> +  if ENV['USE_FRAMEWORKS'] == 'static' && ENV['RCT_NEW_ARCH_ENABLED'] == '1'
```suggestion
  if ENV['USE_FRAMEWORKS'] != nil && ENV['RCT_NEW_ARCH_ENABLED'] == '1'
```

2024-09-11 08:26 UTC, tomekzaw approved these changes

2024-09-11 08:55 UTC, war-in commented
Confirming that PR works in HybridApp 👍

2024-09-11 08:59 UTC, merged