feat: support maxLength prop in web
Expensify/react-native-live-markdown pull request #505
Opened 2024-09-26 08:37 UTC by dominictb

### Details

This PR includes the implementation of `maxLength` prop in web

### Related Issues

https://github.com/Expensify/App/issues/46766

### Manual Tests

1. Paste this text file (over 400k characters) 
[default.txt](https://github.com/user-attachments/files/17113641/default.txt)

2. Check that the text input in both web and native is cut off to 30k length

### Linked PRs

Pending App PR

2024-09-26 10:14 UTC, Skalakid commented
Hello, I'm testing your changes and I found couple of bugs:

1. The input `value` isn't matching the input content. The `value` (in the picture the text under the input) should be the same as the text inside the component

![Screenshot 2024-09-26 at 12 14 49](https://github.com/user-attachments/assets/5412f437-05b6-47df-886e-682c3ad6f277)

2024-09-26 10:21 UTC, Skalakid commented
2. There are some problems with entering text when we reach the `maxLength` limit. Steps:
 - move the cursor to the end of the text (on the `maxLength` index)
 - start typing
 - notice that the old text is being replaced

https://github.com/user-attachments/assets/3dca11e3-60f3-483e-a366-0cc2fc62fe5f

2024-09-26 11:29 UTC, Skalakid commented
Okay, thank you. Now everything works fine :D 

There is one more thing that I wanted to fix there. How about adding value cutting on the first rerender? Currently, when you pass the long text in the `value` prop and the app loads, the `maxLength` prop isn't cutting the input value:

![Screenshot 2024-09-26 at 13 22 47](https://github.com/user-attachments/assets/95d76016-51aa-4a4f-9451-c0d74b9f5ef9)

(On the image, I have `maxLength={5}` and default text passed in the `value` prop)

I know the same thing happens on the default RN TextInput, but I think it's worth fixing in our case. What do you think about it?

2024-09-27 11:46 UTC, Skalakid commented
Bug: Text isn't being replaced when you reach the limit of `maxLength` prop

https://github.com/user-attachments/assets/a1a7b3fe-05bd-4955-a6ef-b65fe769d520

Expected behavior:


https://github.com/user-attachments/assets/5321189d-80c6-422a-a0a9-5f3330995c94

2024-09-30 09:48 UTC, Skalakid reviewed
Overall, it looks good :D Left some small comments

2024-09-30 09:48 UTC, Skalakid commented on src/MarkdownTextInput.web.tsx
> +        if (typeof maxLength === 'number' && parsedText.length > maxLength) {
```suggestion
        if (maxLength !== undefined && parsedText.length > maxLength) {
```

2024-09-30 09:48 UTC, Skalakid commented on src/MarkdownTextInput.web.tsx
> +        if (typeof maxLength === 'number') {
Same here

2024-09-30 09:48 UTC, Skalakid commented on src/MarkdownTextInput.tsx
> +    if (typeof maxLength === 'number') {
```suggestion
    if (maxLength === undefined) {
```

2024-09-30 09:48 UTC, Skalakid commented on src/MarkdownTextInput.tsx
> +    if (typeof maxLength !== 'number' || !value || value.length <= maxLength || !onChangeText) {
```suggestion
    if (maxLength === undefined || !value || value.length <= maxLength || !onChangeText) {
```

2024-10-01 06:32 UTC, Skalakid approved these changes
LGTM

2024-10-01 06:36 UTC, tomekzaw requested changes

2024-10-01 06:36 UTC, tomekzaw commented on src/MarkdownTextInput.tsx
> +        onChangeText={onChangeText}
What if the component was supposed to be uncontrolled? I don't really like this logic here

2024-10-03 07:11 UTC, tomekzaw commented
@dominictb Why can't we just pass `maxLength` prop to `TextInput` in the native implementation?

2024-10-03 10:31 UTC, tomekzaw commented
@dominictb Thanks for the response

> Basically for value > maxLength, native component will just render the whole value without cutting off anything

Isn't it something we should fix directly in react-native?

2024-10-03 10:45 UTC, tomekzaw commented
Actually, a regular `<input type="text">` on web also behaves the same way as currently – if you set `maxlength="10" value="1234567890abcde"`, all 15 characters are visible but you can't edit the text field. I think this is the expected behavior.

2024-10-03 10:53 UTC, Skalakid commented
Okay, @tomekzaw convinced me, let's revert changes on the native side and focus on implementing the `maxLength` prop on the web only. Let's make sure it will work the same as the native one and isn't introducing any new bug

2024-10-03 11:01 UTC, tomekzaw commented
Basically, `maxLength` prop for `MarkdownTextInput` should work the same way as for `TextInput`.

For Android and iOS, let's just pass this prop to `TextInput` just like we already do (via `{...props}`).

For web, we'll need to implement `maxLength` logic since we're using `contenteditable` which doesn't support `maxlength` out-of-the-box.

All other logic should be moved to E/App.

2024-10-04 06:30 UTC, tomekzaw commented
@dominictb Thanks!

2024-10-04 07:49 UTC, Skalakid submitted a review, later dismissed
LGTM

2024-10-04 08:20 UTC, tomekzaw approved these changes

2024-10-07 08:12 UTC, merged